# Generated by Django 4.1 on 2022-08-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_num', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BalanceType',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_sql.balanceaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_sql.class')),
            ],
        ),
        migrations.AddField(
            model_name='balanceaccount',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_sql.uploadedfile'),
        ),
        migrations.AddField(
            model_name='balanceaccount',
            name='subcls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_sql.subclass'),
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets', models.DecimalField(decimal_places=2, max_digits=19)),
                ('liability', models.DecimalField(decimal_places=2, max_digits=19)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_sql.balanceaccount')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_sql.balancetype')),
            ],
        ),
    ]
