# Generated by Django 4.1 on 2022-08-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_num', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('header', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='excel_sql.balanceaccount')),
                ('assets', models.DecimalField(decimal_places=2, max_digits=19)),
                ('liability', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Turnover',
            fields=[
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='excel_sql.balanceaccount')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_sql.class')),
            ],
        ),
        migrations.AddField(
            model_name='balanceaccount',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_sql.uploadedfile'),
        ),
        migrations.AddField(
            model_name='balanceaccount',
            name='subcls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_sql.subclass'),
        ),
    ]
